# Generated by Django 5.2.4 on 2025-12-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_seat_booking_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
