# Generated by Django 5.2.4 on 2026-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcontact',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
