# Generated by Django 5.2.4 on 2026-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_cancelled_at_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
